add installation heading to README.md
homchom/recode pull request #26
Opened 2022-10-31 20:35 UTC by unitOrNull

added an `Installation` heading to `README.md` to have (slightly) more detailed installation instructions

2022-12-28 16:46 UTC, tk2217 requested changes

2022-12-28 16:46 UTC, tk2217 commented on README.md
> +### Building manually
This is generally not something we want to recommend as in development versions can be very unstable and most normal users should not be guided to building an application from source.

2022-12-28 16:46 UTC, tk2217 commented on README.md
> +### GitHub actions
Again, probably unstable and likely better to wait for a beta.

2022-12-28 16:46 UTC, tk2217 commented on README.md
> +## Installation
While putting this in its own area and not having it incorporated into another paragraph is good, we should probably just direct to modrinth as it's more user friendly and I believe it's auto updated when a release is made on GitHub.

2023-01-08 13:33 UTC, unitOrNull commented
after reading tk's comments, this pr is probably not very useful and as they pointed out, it would probably be best to just point them to the modrinth page, so i will be closing this pr

2023-01-08 13:33 UTC, closed without merging