remove try-catch when deserializing (update adventure)
homchom/recode pull request #79
Opened 2024-03-26 20:01 UTC by RedVortexDev

https://github.com/KyoriPowered/adventure/issues/1011 was fixed - no need to try-catch anymore (update adventure accordingly)

2024-03-26 20:02 UTC, RedVortexDev commented
this was tested
![image](https://github.com/homchom/recode/assets/58099979/753448e0-f1f1-4758-8736-9f40b2a66ffc)

2024-03-26 21:49 UTC, homchom requested changes

2024-03-26 21:49 UTC, homchom commented on src/main/java/io/github/homchom/recode/feature/visual/BuiltInResourcePacks.kt
> +        val packDescription = Component.text("[$MOD_ID] ")
You should use the recode `text` function here instead

2024-03-27 14:07 UTC, homchom approved these changes

2024-03-27 14:10 UTC, merged